package cn.tedu.note.dao;

import cn.tedu.note.entity.Note;
import java.util.List;

public interface NoteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbg.generated
     */
    int insert(Note record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbg.generated
     */
    Note selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbg.generated
     */
    List<Note> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Note record);
}