package cn.tedu.note.dao;

import cn.tedu.note.entity.Notebook;
import java.util.List;

public interface NotebookDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbg.generated
     */
    int insert(Notebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbg.generated
     */
    Notebook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbg.generated
     */
    List<Notebook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notebook record);
}