package cn.tedu.note.entity;

public class Note {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_notebook_id
     *
     * @mbg.generated
     */
    private String notebookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_status_id
     *
     * @mbg.generated
     */
    private String statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_type_id
     *
     * @mbg.generated
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_last_modify_time
     *
     * @mbg.generated
     */
    private Long lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_body
     *
     * @mbg.generated
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_id
     *
     * @return the value of cn_note.cn_note_id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_id
     *
     * @param id the value for cn_note.cn_note_id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_notebook_id
     *
     * @return the value of cn_note.cn_notebook_id
     *
     * @mbg.generated
     */
    public String getNotebookId() {
        return notebookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_notebook_id
     *
     * @param notebookId the value for cn_note.cn_notebook_id
     *
     * @mbg.generated
     */
    public void setNotebookId(String notebookId) {
        this.notebookId = notebookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_user_id
     *
     * @return the value of cn_note.cn_user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_user_id
     *
     * @param userId the value for cn_note.cn_user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_status_id
     *
     * @return the value of cn_note.cn_note_status_id
     *
     * @mbg.generated
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_status_id
     *
     * @param statusId the value for cn_note.cn_note_status_id
     *
     * @mbg.generated
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_type_id
     *
     * @return the value of cn_note.cn_note_type_id
     *
     * @mbg.generated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_type_id
     *
     * @param typeId the value for cn_note.cn_note_type_id
     *
     * @mbg.generated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_title
     *
     * @return the value of cn_note.cn_note_title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_title
     *
     * @param title the value for cn_note.cn_note_title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_create_time
     *
     * @return the value of cn_note.cn_note_create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_create_time
     *
     * @param createTime the value for cn_note.cn_note_create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_last_modify_time
     *
     * @return the value of cn_note.cn_note_last_modify_time
     *
     * @mbg.generated
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_last_modify_time
     *
     * @param lastModifyTime the value for cn_note.cn_note_last_modify_time
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_body
     *
     * @return the value of cn_note.cn_note_body
     *
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_body
     *
     * @param body the value for cn_note.cn_note_body
     *
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body;
    }
}