package cn.tedu.note.entity;

import java.util.Date;

public class Notebook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_notebook_id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_notebook_type_id
     *
     * @mbg.generated
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_notebook_name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_notebook_createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook.cn_notebook_desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_notebook_id
     *
     * @return the value of cn_notebook.cn_notebook_id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_notebook_id
     *
     * @param id the value for cn_notebook.cn_notebook_id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_user_id
     *
     * @return the value of cn_notebook.cn_user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_user_id
     *
     * @param userId the value for cn_notebook.cn_user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_notebook_type_id
     *
     * @return the value of cn_notebook.cn_notebook_type_id
     *
     * @mbg.generated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_notebook_type_id
     *
     * @param typeId the value for cn_notebook.cn_notebook_type_id
     *
     * @mbg.generated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_notebook_name
     *
     * @return the value of cn_notebook.cn_notebook_name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_notebook_name
     *
     * @param name the value for cn_notebook.cn_notebook_name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_notebook_createtime
     *
     * @return the value of cn_notebook.cn_notebook_createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_notebook_createtime
     *
     * @param createtime the value for cn_notebook.cn_notebook_createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook.cn_notebook_desc
     *
     * @return the value of cn_notebook.cn_notebook_desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook.cn_notebook_desc
     *
     * @param desc the value for cn_notebook.cn_notebook_desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}