package cn.tedu.note.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_nick
     *
     * @mbg.generated
     */
    private String nick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_id
     *
     * @return the value of cn_user.cn_user_id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_id
     *
     * @param id the value for cn_user.cn_user_id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_name
     *
     * @return the value of cn_user.cn_user_name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_name
     *
     * @param name the value for cn_user.cn_user_name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_password
     *
     * @return the value of cn_user.cn_user_password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_password
     *
     * @param password the value for cn_user.cn_user_password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_token
     *
     * @return the value of cn_user.cn_user_token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_token
     *
     * @param token the value for cn_user.cn_user_token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_nick
     *
     * @return the value of cn_user.cn_user_nick
     *
     * @mbg.generated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_nick
     *
     * @param nick the value for cn_user.cn_user_nick
     *
     * @mbg.generated
     */
    public void setNick(String nick) {
        this.nick = nick;
    }
}